name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment (dev or prod)"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod
  push:
    branches:
      - workflow

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-south-2

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Init
        run: terraform init
        working-directory: Terraform

      - name: Destroy Terraform Infrastructure
        run: terraform destroy -auto-approve --var-file="${{ github.event.inputs.environment }}.tfvars"
        working-directory: Terraform
