name: Terraform Resource Report

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment (dev or prod)"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod

jobs:
  resource-report:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-south-2

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Init
        run: terraform init
        working-directory: Terraform

      - name: Select/Create Workspace
        run: |
          terraform workspace select ${{ github.event.inputs.environment }}
        working-directory: Terraform

      - name: Generate Resource Report
        run: |
          chmod +x ./scripts/resource_report.sh
          ./scripts/resource_report.sh > resources.json
        working-directory: Terraform

      - name: Upload Resource Report
        uses: actions/upload-artifact@v4
        with:
          name: terraform-resources
          path: Terraform/resources.json
